sudo: required
language: node_js
node_js:
  - 8

services:
  - docker

before_script:
  - sudo service mysql stop
  - sudo service postgresql stop
  - docker-compose up -d

before_install:
  - npm install -g lerna

install:
  - npm install
  - lerna bootstrap

script:
  - npm run lint
  - lerna run test
  - lerna run e2e