version: '3'
services:

  mysql:
    image: "mysql:5.7.10"
    ports:
      # Another version of MySQL is installed on the vm and already uses the port 3306.
      - "3308:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_DATABASE: "test"

  mariadb:
    image: "mariadb:10.1.16"
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: "admin"
      MYSQL_USER: "test"
      MYSQL_PASSWORD: "test"
      MYSQL_DATABASE: "test"

  postgres:
    image: "postgres:9.6.1"
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "test"
      POSTGRES_PASSWORD: "test"
      POSTGRES_DB: "test"

  # mssql:
  #   image: "microsoft/mssql-server-linux:2017-GA"
  #   ports:
  #     - "1433:1433"
  #   environment:
  #     SA_PASSWORD: "Admin12345"
  #     ACCEPT_EULA: "Y"

  mongodb:
    image: "mongo:3.4.1"
    ports:
      - "27017:27017"
  
  redis:
    image: "redis:4.0.14"
    ports:
      - "6379:6379"

  adminer:
    image: adminer
    ports:
      - 8080:8080