port: 3001

settings:
  csrf: false
  debug: false
  loggerFormat: tiny
  staticPath: public/
  session:
    cookie:
      path: /
    resave: false
    saveUnitialized: false
    secret: my-secret

database:
  database: './db.sqlite3'