name: Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x, 12.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install global dependencies (lerna, pm2, codecov)
      run: |
        npm install -g lerna
        npm install -g pm2
        npm install -g codecov
    - name: Install dependencies and build the packages
      run: |
        npm install
        lerna bootstrap
      
