name: Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8, 10]

    env:
      AUTH0_DOMAIN: ${{ secrets.AUTH0_DOMAIN }}
      AUTH0_AUDIENCE: ${{ secrets.AUTH0_AUDIENCE }}
      AUTH0_TOKEN: ${{ secrets.AUTH0_TOKEN }}
      SETTINGS_AWS_ACCESS_KEY_ID: ${{ secrets.SETTINGS_AWS_ACCESS_KEY_ID }}
      SETTINGS_AWS_SECRET_ACCESS_KEY: ${{ secrets.SETTINGS_AWS_SECRET_ACCESS_KEY }}
      NODE_VERSION: ${{ matrix.node-version }}

    services:
      mysql:
        image: mysql:5.7.10
        ports:
          # Another version of MySQL is installed on the vm and already uses the port 3306.
          - 3308:3306
        env:
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_USER: test
          MYSQL_PASSWORD: test
          MYSQL_DATABASE: test

      mariadb:
        image: mariadb:10.1.16
        ports:
          - 3307:3306
        env:
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_USER: test
          MYSQL_PASSWORD: test
          MYSQL_DATABASE: test

      postgres:
        image: postgres:9.6.1
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test

      mongodb:
        image: mongo:3.4.1
        ports:
          - 27017:27017

      redis:
        image: redis:4.0.14
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install global dependencies (lerna, pm2, codecov)
      run: npm install -g lerna pm2 codecov
    - name: Install project dependencies
      run: npm install
    - name: Install package dependencies and build packages
      run: lerna bootstrap
    - name: Create CLI symlink in the global folder
      run: npm link
      working-directory: packages/cli
    - name: Check package linting
      run: npm run lint
    - name: Run unit tests of @foal/acceptance-tests
      run: cd acceptance-tests && npm run test
    - name: Run unit tests of @foal/aws-s3
      run: cd aws-s3 && npm run test
    - name: Run unit tests of @foal/cli
      run: cd cli && npm run test
    - name: Run unit tests of @foal/csrf
      run: cd csrf && npm run test
    - name: Run unit tests of @foal/ejs
      run: cd ejs && npm run test
    - name: Run unit tests of @foal/examples
      run: cd examples && npm run test
    - name: Run unit tests of @foal/formidable
      run: cd formidable && npm run test
    - name: Run unit tests of @foal/graphql
      run: cd graphql && npm run test
    - name: Run unit tests of @foal/jwks-rsa
      run: cd jwks-rsa && npm run test
    - name: Run unit tests of @foal/jwt
      run: cd jwt && npm run test
    - name: Run unit tests of @foal/mongodb
      run: cd mongodb && npm run test
    - name: Run unit tests of @foal/mongoose
      run: cd mongoose && npm run test
    - name: Run unit tests of @foal/password
      run: cd password && npm run test
    - name: Run unit tests of @foal/redis
      run: cd redis && npm run test
    - name: Run unit tests of @foal/social
      run: cd social && npm run test
    - name: Run unit tests of @foal/storage
      run: cd storage && npm run test
    - name: Run unit tests of @foal/swagger
      run: cd swagger && npm run test
    - name: Run unit tests of @foal/typeorm
      run: cd typeorm && npm run test
    - name: Run unit tests of @foal/typestack
      run: cd typestack && npm run test
    - name: Run unit tests of @foal/core
      run: cd core && npm run test
    - name: Run acceptance tests (Bash)
      run: ./e2e_test.sh
    - name: Send code coverage report to Codecov
      uses: codecov/codecov-action@v1.0.3
      with:
        token: ${{secrets.CODECOV_TOKEN}}
        file: packages/core/coverage/*.json
