name: Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x]

    services:
      # mysql is already installed on ubuntu
      # mysql:
      #   image: mysql:5.7.10
      #   ports:
      #     - 3306:3306
      #   env:
      #     MYSQL_ROOT_PASSWORD: admin
      #     MYSQL_USER: test
      #     MYSQL_PASSWORD: test
      #     MYSQL_DATABASE: test

      mariadb:
        image: mariadb:10.1.16
        ports:
          - 3307:3306
        env:
          MYSQL_ROOT_PASSWORD: admin
          MYSQL_USER: test
          MYSQL_PASSWORD: test
          MYSQL_DATABASE: test

      postgres:
        image: postgres:9.6.1
        ports:
          - 5432:5432
        env:
          POSTGRES_USER: test
          POSTGRES_PASSWORD: test
          POSTGRES_DB: test

      mongodb:
        image: mongo:3.4.1
        ports:
          - 27017:27017

      redis:
        image: redis:4.0.14
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install global dependencies (lerna, pm2, codecov)
      run: npm install -g lerna pm2 codecov
    - name: Install project dependencies
      run: npm install
    - name: Install package dependencies and build packages
      run: |
        lerna bootstrap
        cd packages/cli && npm link && cd ../..
    - name: Check package linting
      run: npm run lint
    - name: Run unit and acceptance tests (TypeScript)
      run: lerna run --no-bail test
    - name: Run acceptance tests (Bash)
      run: ./e2e_test.sh
