name: Test

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x, 10.x]

    services:
      redis:
        image: "redis:4.0.14"
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install global dependencies (lerna, pm2, codecov)
      run: npm install -g lerna pm2 codecov
    - name: Install project dependencies
      run: npm install
    - name: Install package dependencies and build packages
      run: |
        lerna bootstrap
        cd packages/cli && npm link && cd ../..
    - name: Check package linting
      run: npm run lint
    - name: Run unit and acceptance tests (TypeScript)
      run: lerna run --no-bail test
    - name: Run acceptance tests (Bash)
      run: ./e2e_test.sh
